#include "lap_test.h"

#include "../tester.h"

#include "immintr.h"
#include "mem.h"
#include "rand.h"
#include "types.h"

AS_RESULT(lap_result_t);

// TODO: Move to autogenerated header
/* #define TRIES 1000 */
#define TRIES 10

void sort(u64 arr[], int n) {
  u64 i, j, temp;
  for (i = 0; i < n - 1; i++) {
    for (j = 0; j < n - i - 1; j++) {
      if (arr[j] > arr[j + 1]) {
        // Swap arr[j] and arr[j+1]
        temp = arr[j];
        arr[j] = arr[j + 1];
        arr[j + 1] = temp;
      }
    }
  }
}

u64 median(u64 arr[], int n) {
  sort(arr, n);
  return arr[n / 2];
}

u64 measure(volatile u32 *arr, int iters) {
  u64 timings[TRIES] = {0};
  u64 t0, t1;
  volatile register int junk = 0;

  // Dry run
  junk = 0;
  for (int i = 0; i < iters; ++i) {
    junk = arr[junk];
  }

  for (int i = 0; i < TRIES; ++i) {
    junk = 0;
    t0 = get_cycle();
    for (int i = 0; i < iters; ++i) {
      junk = arr[junk];
    }
    t1 = get_cycle();
    timings[i] = t1 - t0;
  }

  return median(timings, TRIES);
}

u64 measure_unroll(volatile u32 *arr, int iters) {
  u64 timings[TRIES] = {0};
  u64 t0, t1;
  volatile register int junk = 0;

  // Dry run
  junk = 0;
  for (int i = 0; i < iters; ++i) {
    junk = arr[junk];
  }

  for (int i = 0; i < TRIES; ++i) {
    junk = 0;
    t0 = get_cycle();
#pragma GCC unroll 10
    for (int i = 0; i < iters; ++i) {
      junk = arr[junk];
    }
    t1 = get_cycle();
    timings[i] = t1 - t0;
  }

  return median(timings, TRIES);
}

void func(request_dependencies_t *args) {

  const int PAGE_SIZE = 4096;
  const int STRIDE = 8;

  /* const int iters = 400; */
  const int iters = 10;

  const int NUM_PAGES_BUF = 1 + (iters * STRIDE * sizeof(int)) / PAGE_SIZE;
  u32 *buf = alloc(NUM_PAGES_BUF * PAGE_SIZE);
  for (u32 i = 0; i < NUM_PAGES_BUF * PAGE_SIZE; i++) {
    ((u8 *)buf)[i] = 0;
  }

  const int WRITE_MAX = NUM_PAGES_BUF * PAGE_SIZE / sizeof(int);

  for (int i = 0; i < WRITE_MAX; ++i) {
    buf[i] = get_rand() % WRITE_MAX;
  }

  RESULT->random_time_unroll = measure_unroll(buf, iters);
  RESULT->random_time = measure(buf, iters);

#ifdef MITIGATE
  RESULT->fixed_time_unroll = RESULT->random_time_unroll;
  RESULT->fixed_time = RESULT->random_time;
#else

  int index = 0;
  while (index + STRIDE < WRITE_MAX) {
    buf[index] = index + STRIDE;
    index += STRIDE;
  }

  RESULT->fixed_time_unroll = measure_unroll(buf, iters);
  RESULT->fixed_time = measure(buf, iters);
#endif
  /* printf("%lld\n", RESULT->fixed_time_unroll); */
}

#include "../tester.c"
